"""Add review  model

Revision ID: 7ea8a522a3c9
Revises: b0acaadb1b4a
Create Date: 2023-12-23 22:46:04.813695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea8a522a3c9'
down_revision: Union[str, None] = 'b0acaadb1b4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
